
pipeline {
    agent {
        label 'svxe-build-agent'
    }
    tools {
        maven 'mvn'
        jdk 'JDK17-OPEN'
    }
    parameters {
        choice(
            name: 'target',
            choices: ['pq-1', 'pq-2'],
            description: 'Select the deployment target'
        )
    }
}








//  checkout([$class: 'GitSCM',
//     branches: [[name: '*/feature/devops-anuncement']],
//     doGenerateSubmoduleConfigurations: false,
//     extensions: [],
//     submoduleCfg: [],
//     userRemoteConfigs: [[credentialsId: '123456789875464364364', url: 'https://ghdp1.devops.jamschool.com/PQ/sgs-web.git']]
// ])
